version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
       - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: banco-beer-database
    ports:
      - "6033:3306"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=guest
      - RABBITMQ_PASS=guest
      - RABBITMQ_DEFAULT_VHOST=/
      - HEALTH_CHECK_CACHE=0
    ports:
      - 15672:15672
      - 5672:5672

volumes:
  database: